import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import { SessionProvider } from "next-auth/react";
import getCurrentUser from "./actions/getCurrentUser";
import Script from "next/script";
import ToastiProvider from "@/components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={currentUser} />
        <ToastiProvider />
        {children}
        <Script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=42c741981743a10085c06db7f49f9f2d&libraries=services,clusterer&autoload=false" />
      </body>
    </html>
  );
}
